In [33]:
from statistics import mode

In [1]:
import pandas as pd

In [3]:
data_final = pd.read_csv("data2.csv")

In [4]:
data_final

                                               Sentence Sentiment
0     The GeoSolutions technology will leverage Bene...  positive
1     $ESI on lows, down $1.50 to $2.50 BK a real po...  negative
2     For the last quarter of 2010 , Componenta 's n...  positive
3     According to the Finnish-Russian Chamber of Co...   neutral
4     The Swedish buyout firm has sold its remaining...   neutral
...                                                 ...       ...
5837  RISING costs have forced packaging producer Hu...  negative
5838  Nordic Walking was first used as a summer trai...   neutral
5839  According shipping company Viking Line , the E...   neutral
5840  In the building and home improvement trade , s...   neutral
5841  HELSINKI AFX - KCI Konecranes said it has won ...  positive

[5842 rows x 2 columns]

In [5]:
data3 = pd.read_csv("data3.csv")

In [6]:
data3

,Date_published,Headline,Synopsis,Full_text,Final Status
0,2022-06-21,"Banks holding on to subsidy share, say payment...",The companies have written to the National Pay...,ReutersPayments companies and banks are at log...,Negative
1,2022-04-19,Digitally ready Bank of Baroda aims to click o...,"At present, 50% of the bank's retail loans are...",AgenciesThe bank presently has 20 million acti...,Positive
2,2022-05-27,Karnataka attracted investment commitment of R...,Karnataka is at the forefront in attracting in...,PTIKarnataka Chief Minister Basavaraj Bommai.K...,Positive
3,2022-04-06,Splitting of provident fund accounts may be de...,The EPFO is likely to split accounts only at t...,Getty ImagesThe budget for FY22 had imposed in...,Negative
4,2022-06-14,Irdai weighs proposal to privatise Insurance I...,"Set up in 2009 as an advisory body, IIB collec...",AgenciesThere is a view in the insurance indus...,Positive
...,...,...,...,...,...
395,2022-06-10,"Banks take a cue from RBI, hike lending rates",These banks raised their respective external b...,"PTIICICI Bank, Bank of Baroda, Punjab National...",Negative
396,2022-06-29,Sebi issues Rs 27 lakh recovery notice to indi...,"In the event of non-payment, it will recover t...",ReutersThe logo of the Securities and Exchange...,Negative
397,2022-06-06,Apollo Hospital shares drop 0.68% as Sensex ...,"A total of 10,105 shares changed hands on the ...",Getty ImagesShrikant Chouhan of Kotak Securiti...,Negative
398,2022-05-16,SBI at Rs 710? What makes analysts see up to 5...,Calling the stock 'attractively valued' analys...,AgenciesThe PSU bank reported a 41.27 per cent...,Positive
399,2022-05-27,Stock market update: Mining stocks up as mar...,The 30-share BSE Sensex was up 323.71 points...,Shutterstock.comAgarwal said the global econom...,Positive

In [7]:
data3 = data3.drop(["Date_published"] , axis = 1)
data3["Full_text"] = data3["Headline"] + data3["Full_text"] + data3["Synopsis"]

In [8]:
data3.drop(["Synopsis" , "Headline"] , axis =1 , inplace = True)

In [18]:
data3 = data3.rename(columns = {"Full_text" : "Sentence" , "Final Status" : "Sentiment"})

In [21]:
data_final = pd.merge(data_final , data3 , how = "outer")

In [24]:
data_final

                                               Sentence Sentiment
0     #Apple breaks major support, here are some lev...  negative
1     #Apple up almost 20% from its February lows wi...  positive
2     #Fintech provider $CAFN Cachet Financial Solut...  positive
3     #FusionIQ NEW Positive Timing Signal on $SBUX ...  positive
4     #LongPos $TSLA 256 Break-out thru 50 & 200- DM...  positive
...                                                 ...       ...
6237  what #stocks large players are selling http://...  negative
6238  what is up with $HK..... from Jan to now it's ...  negative
6239  www.countryelements.co.uk Designed by Patricia...   neutral
6240                  zip , '' experts warned Tuesday .   neutral
6241                                                NaN  Negative

[6242 rows x 2 columns]

In [25]:
data4 = pd.read_csv("data4.csv")

In [ ]:
data4.drop(["Words" , "S.No"] , axis = 1 , inplace = True)

In [42]:
sentiments = [mode(eval(x).values()) for x in data4["Decisions"]]

In [ ]:
data4["Sentiments"] = sentiments
data4.drop(["Decisions"] , axis  = 1 , inplace = True)

                                                Sentence Sentiment
0      SpiceJet to issue 6.4 crore warrants to promoters   neutral
1                      MMTC Q2 net loss at Rs 10.4 crore   neutral
2      Mid-cap funds can deliver more, stay put: Experts  positive
3                 Mid caps now turn into market darlings  positive
4      Market seeing patience, if not conviction: Pra...   neutral
...                                                  ...       ...
10748       Negative on Chambal, Advanta: Mitesh Thacker  negative
10749     Small, Mid-cap stocks may emerge outperformers  positive
10750                      Rupee slips against US dollar  negative
10751                       Rupee weak against US dollar  negative
10752                Australia shares flat; energy drags   neutral

[10753 rows x 2 columns]

In [48]:
data4.rename(columns = {"Title" : "Sentence" , "Sentiments" : "Sentiment"} , inplace = True)

In [51]:
data_final = pd.merge(data_final , data4 , how = 'outer')

In [57]:
data1 = pd.read_csv("data1.csv" , encoding="ISO-8859-1")

In [58]:
data1

     Sentiment                                           Sentence
0      neutral  According to Gran , the company has no plans t...
1      neutral  Technopolis plans to develop in stages an area...
2     negative  The international electronic industry company ...
3     positive  With the new production plant the company woul...
4     positive  According to the company 's updated strategy f...
...        ...                                                ...
4841  negative  LONDON MarketWatch -- Share prices ended lower...
4842   neutral  Rinkuskiai 's beer sales fell by 6.5 per cent ...
4843  negative  Operating profit fell to EUR 35.4 mn from EUR ...
4844  negative  Net sales of the Paper segment decreased to EU...
4845  negative  Sales in Finland decreased by 10.5 % in Januar...

[4846 rows x 2 columns]

In [61]:
import codecs
def hash_rep(error) :
    return ("###" , error.start+1)
codecs.register_error('hash_rep' , hash_rep)
new_strs = []
for i in range(len(data1)): 
    new_strs.append(data1["Sentence"][i].encode('utf-8' , errors = 'hash_rep').decode('utf-8'))

In [73]:
import re
for idx , s in enumerate(new_strs):
    if re.search(r"###" , s):
        print(idx , s)

In [75]:
data1 = pd.DataFrame({"Sentiment" : data1["Sentiment"] , "Sentence" : new_strs})

In [76]:
data1

     Sentiment                                           Sentence
0      neutral  According to Gran , the company has no plans t...
1      neutral  Technopolis plans to develop in stages an area...
2     negative  The international electronic industry company ...
3     positive  With the new production plant the company woul...
4     positive  According to the company 's updated strategy f...
...        ...                                                ...
4841  negative  LONDON MarketWatch -- Share prices ended lower...
4842   neutral  Rinkuskiai 's beer sales fell by 6.5 per cent ...
4843  negative  Operating profit fell to EUR 35.4 mn from EUR ...
4844  negative  Net sales of the Paper segment decreased to EU...
4845  negative  Sales in Finland decreased by 10.5 % in Januar...

[4846 rows x 2 columns]

In [78]:
data_final = pd.merge(data_final , data1 , how = 'outer')

In [79]:
data_final.isnull().sum()

Sentence     1
Sentiment    0
dtype: int64

In [ ]:
data_final.dropna(inplace = True)
data_final["Sentiment"] = data_final["Sentiment"].str.lower()

In [84]:
data_final.to_csv('final_data.csv')